name: Angular Lint

on:
  push:
    branches:
      - main # Run on pushes to the main branch
      - develop # Run on pushes to the develop branch (if you have one)
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest # Or windows-latest, or macOS-latest, depending on your preference

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Action to check out your repository's code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version suitable for your Angular project
          cache: 'npm' # Cache npm dependencies for faster installs
          cache-dependency-path: 'package-lock.json' # Path to your package-lock.json

      - name: Install Dependencies
        run: npm ci # Use 'npm ci' for clean installs in CI/CD environments

      - name: Run Angular Lint
        run: npm run lint # Executes the 'lint' script defined in your package.json
        # If your lint command is specific to a project in a monorepo, you might use:
        # run: ng lint your-project-name
        # Or if it's a specific configuration:
        # run: ng lint --configuration production